### ISSUE TITLE
dashboard中查询不到数据

### ISSUE THREAD

**Issue by wkshare** [open-falcon/dashboard#1]
falcon_portal数据库中的host表，有对应的主机。

dashboard没有错误日志。
hbs没有错误日志。

如何定位问题原因？

**Comment by freedomkk-qfeng** [comment]
同问，使用 docker 版本测试，dashboard 中有对应主机和采集的counter，但是点开counter没有绘出图来

**Comment by niean** [comment]
book.open-falcon.com, Faq，绘图问题

**Comment by EverChris** [comment]
搞什么飞机啊，dashboard这个组件我换了n台机器都装不上

**Comment by pobearm** [comment]
是啊, 我装了6遍, dashboard都跑不起来

**Comment by itxx00** [comment]
@EverChris  @pobearm  仔细看文档按照文档描述安装和排查问题，如果装不上就提供你们的相关报错信息，不然怎么帮你们呢？

**Comment by hiawui** [comment]
@freedomkk-qfeng 请问你的问题解决了吗？

**Comment by hiawui** [comment]
@itxx00 我遇到了和 @freedomkk-qfeng 一样的问题，按照faq的说明查了进程和日志，都没有发现有异常。这个问题应该是好多人都遇到过吧？应该怎么解决呢？

**Comment by hiawui** [comment]
@laiwei 求助。。。。

**Comment by laiwei** [comment]
@hiawui 出错信息是什么

**Comment by hiawui** [comment]
并没有出错信息，打开chrome调试看到 /chart/h?cf=AVERAGE&end=1493126976&graph_type=h&id=8&start=1493123436&sum=off&sumonly=off 这个调用， 返回数据是 {"units": "", "series": [], "title": "cpu.idle"}

**Comment by hiawui** [comment]
@laiwei 并没有出错信息，打开chrome调试看到 /chart/h?cf=AVERAGE&end=1493126976&graph_type=h&id=8&start=1493123436&sum=off&sumonly=off 这个调用， 返回数据是 {"units": "", "series": [], "title": "cpu.idle"}
