### ISSUE TITLE
图表显示数据延时

### ISSUE THREAD

**Issue by LittlePeng** [open-falcon/dashboard#10]
使用API以5s间隔时间push数据，用于实时观察接口调用情况，发现：
1. dashboard 分别率最低30s
2. 数据延时，延时将近5分钟

另外: 可否提供类似Google charts开源图表那种 鼠标移动上去时，显示标尺和每条线的数值，现在必须点到对应线上确定时间点才显示，线多的时候很很难看清楚。

**Comment by LittlePeng** [comment]
2. 数据延时，延时将近5分钟

这个问题已经大概知道了，ajax请求上传本地end时间，两机器时间差造成读取延时，而且end为本机时间-60s（应该是考虑1分钟一个点吧）； 考虑使用将begin~end 改成 最近xx 时间 就没有时钟不一致的问题了吧。

**Comment by LittlePeng** [comment]
RRD 1分钟一个点，实际图却是30s一个点，我修改graph RRD 采集到5s 一次但不生效呢？

**Comment by LittlePeng** [comment]
已解决

**Comment by laiwei** [comment]
@LittlePeng 嗯，30秒一个点，在book.open-falcon.com 里面，有相关描述。我的微信 hellolaiwei ，有问题可以再沟通

**Comment by LittlePeng** [comment]
@laiwei ok, 我再仔细看看
