### ISSUE TITLE
dashboard菜单报错

### ISSUE THREAD

**Issue by EnglishVillage** [open-falcon/dashboard#106]
使用open-falcon版本0.2.1,dashboard版本0.2.0,python版本2.7
打开dashboard中的Hostgroups,Templates,Expressions,Nodata,Alarm-Dashboard菜单会报错.如下:
报错菜单:
![1531989860 1](https://user-images.githubusercontent.com/19756879/42931740-0d48d50a-8b73-11e8-93e2-bdd6c28c0527.png)
报错信息:
![wechat _20180719161807](https://user-images.githubusercontent.com/19756879/42930448-9b8acfd4-8b6f-11e8-8d73-a3a9948db8a1.png)

**Comment by sfp1982** [comment]
这个怎么解决的吗
