### ISSUE TITLE
Blind SQL Injection

### ISSUE THREAD

**Issue by solozly** [open-falcon/dashboard#128]
This script is possibly vulnerable to SQL Injection attacks
An attacker may execute arbitrary SQL statements on the vulnerable system. This may compromise the integrity of your database and/or expose sensitive information. 

http://127.0.0.1:8081/user/list?query=1   vulnerability:'query'

Your script should filter metacharacters from user input. 
Check detailed information for more information about fixing this vulnerability

eg:
<img width="1435" alt="1" src="https://user-images.githubusercontent.com/48704088/58527868-0adabc80-8207-11e9-8564-f38abdd5b14e.png">

**Comment by laiwei** [comment]
@solozly  Thank you for the report. This issue is fixed at https://github.com/open-falcon/falcon-plus/pull/733
