### ISSUE TITLE
按照文档安装完，访问页面静态文件500

### ISSUE THREAD

**Issue by carlguo2016** [open-falcon/dashboard#136]
按照文档安装完，访问页面，不能正常显示，css, 图片，js等500错误

**Comment by plutolqw** [comment]
同样遇到这个问题，怎么解决？

**Comment by canghai908** [comment]
修改pip_requirements.txt文件,
```
Werkzeug>=0.11.15
```
之后
```
./env/bin/pip install -r pip_requirements.txt -i https://pypi.douban.com/simple
```
重启应用即可

**Comment by carlguo2016** [comment]
可以了，十分感谢

**Comment by laiwei** [comment]
这个 PR 合并了  https://github.com/open-falcon/dashboard/pull/134

**Comment by laiwei** [comment]
fixed https://github.com/open-falcon/dashboard/pull/138

@carlguo2016 @plutolqw
