### ISSUE TITLE
dashboard似乎不该假定用户一定使用virtualenv部署

### ISSUE THREAD

**Issue by xiaowing** [open-falcon/dashboard#21]
尝试部署了一下open-falcon，在部署到dashboard时碰到一个问题，想和大家探讨一下：

wsgi.py中有如下代码：
```python
activate_this = '%s/env/bin/activate_this.py' % base_dir
execfile(activate_this, dict(__file__=activate_this))
```

这个代码的前提假设是认为用户一定会使用virtualenv进行部署。
但我认为，只要依赖条件满足了， 应该与我是用virtualenv部署还是用系统Python运行时部署没有关系，因此这个假定条件有点武断了。
_在我的环境下，我直接使用的是系统python运行时，因此直接把这两句话给注掉了_

是否可以考虑在上述代码中加个判断条件? 比如:

```python
activate_this = '%s/env/bin/activate_this.py' % base_dir
if os.path.isfile(activate_this):
    execfile(activate_this, dict(__file__=activate_this))
```

欢迎大家指正。

**Comment by laiwei** [comment]
嗯，谢谢指正。官方的安装步骤中，会指引用户 使用virtualenv，是一种最佳实践

**Comment by xiaowing** [comment]
谢谢快速反馈。

目前官方文档确实也指引大家去用virtualenv了，不过我认为virtualenv虽然算是最佳实践，但是也不应该是唯一选项。

事实上我觉得贵Team的 Open-Falcon/Portal组件中处理得相对友善一点。 它尝试通过 source env/bin/activate来尝试进入沙盒环境。如果没有的话，它会报一个错，但是不影响后面执行，至于后面到底能不能执行，则看默认的Python运行时能不能满足条件了，它本身并不去做强制约束。

以上纯粹个人观点，欢迎探讨～
