### ISSUE TITLE
dashboard出现如下warning，当前图形也查不出

### ISSUE THREAD

**Issue by wkshare** [open-falcon/dashboard#3]
空白页面

query中诶呀

/home/falcon/dashboard/rrd/store.py:38: Warning: Data truncated for column 'counters' at row 1
  cursor.execute(*a, **kw)
/home/falcon/dashboard/rrd/store.py:38: Warning: Data truncated for column 'counters' at row 1
  cursor.execute(*a, **kw)

**Comment by niean** [comment]
空白页应该和这个没关系。

**Comment by niean** [comment]
私聊下吧。我的Q 1395673871，加下~

2015-06-18 12:06 GMT+08:00 wkshare <notifications@github.com>:
