### ISSUE TITLE
falco-screen没有图形展示

### ISSUE THREAD

**Issue by claybbs** [open-falcon/dashboard#4]
![image](https://cloud.githubusercontent.com/assets/7273149/9902181/014dfbe6-5c9f-11e5-86b2-a57cf9b40df2.png)

**Comment by itxx00** [comment]
貌似你没有搞对哦，cpu.ide是个什么东西，应该是idle吧，提交issue之前一定要仔细查看官方文档，

**Comment by claybbs** [comment]
已经找到原因了，thanks.
