### ISSUE TITLE
dashboard中screen页面，添加graph里的counter，不能按照metric和tags条件选择，只能写整行counter

### ISSUE THREAD

**Issue by lovefalcon** [open-falcon/dashboard#47]

**Comment by laiwei** [comment]
截图看看？

**Comment by laiwei** [comment]
fixed:)

- api: https://github.com/open-falcon/falcon-plus/commit/29f6b0046f8445ae6ad229d64b5c3b68747b7dda
- dashboard: https://github.com/open-falcon/dashboard/commit/999935e3caf4974f39b7f245943cd685f8dc2344
