### ISSUE TITLE
dashboard查看图的时候保存screen功能

### ISSUE THREAD

**Issue by modeyang** [open-falcon/dashboard#6]
1、用了一段时间open-falcon后，发现dashboard对于添加screen时需要反复来回添加host和metrics， 可不可以在dashboard主界面看图的界面上有个保存为screen的功能？
2、在两次不同的counter条件搜索后选定后的counters不能同时显示，后面勾选的counter会覆盖前一次的counter，这算个bug吗？ 
谢谢

**Comment by niean** [comment]
1. 可以。等后续版本增加。
2. 不是bug。两次查询不相干。

聂安

**Comment by modeyang** [comment]
对于2  确实如此，在dashboard当同时搜索多个关键字时，提醒“可以用空格分割多个搜索关键字”，但是貌似没有实现正确。同时搜索“mem disk” 就提示搜索失败。

**Comment by laiwei** [comment]
对于2，你所描述的“没有实现正确”，能更详细的描述下么

谢谢
