### ISSUE TITLE
给dashboard server配置url前缀的功能

### ISSUE THREAD

**Issue by codepiano** [open-falcon/dashboard#7]
如果在nginx中配置了反向代理，并且location不是 「/」，无法访问到后端的flask服务器

现在的dashboard无法配置server context作为统一的url前缀

**Comment by laiwei** [comment]
需要我们怎么做？

**Comment by codepiano** [comment]
@laiwei 
现在dashborad的页面、ajax请求和静态资源的url全部使用根路径 '/' 开头，没有一个公共的url前缀，比如
/falcon/xxx.html  /falcon/xxx.js 
如果所有的url都有一个前缀，比如上面的 'falcon' ，配置nginx方向代理规则的时候就会很方便，我只要把所有 /falcon 开头的请求 proxy_pass 到 host:port 上就可以了。

我遇到的问题是我们有台 server，里面部署的是沙盒环境，通过nginx反向代理到各个服务，对外只提供 80 端口进行访问。现在要把 falcon 也配置到这台 server 里面，配一个反向代理前缀 '/falcon'，访问的时候通过 sandbox.example.com/falcon 进行访问，现在这种方式是行不通的，由于静态资源和ajax请求全部使用 '/' 开头，无法被识别为是到 dashboard 服务器的请求。

我下午抽空修改了一下 dashborad 的代码，替换了所有的相关url和api route，现在已经可以正常工作在nginx后端。如果要修改的话，大概就是类似我这种改发，处理api和静态资源的引用方式：

https://github.com/codepiano/dashboard/commit/7f94760412deda3158cc93de4061017d1dc56a88

**Comment by sam2099** [comment]
@codepiano  你反向代理 transfer 和 heartbeat 吗？
