### ISSUE TITLE
open-falcon如何设置监听浮动ip的端口?

### ISSUE THREAD

**Issue by jschunlei** [open-falcon/dashboard#70]
我们的服务器是用pacemaker这种工具做的冷双机,同一时间只在一边启动进程,进程和浮动ip关联,现在发现配置的时候,配置浮动ip的监听端口,无法告警!!

**Comment by CastroKKK** [comment]
同问，目前很多工作进程、组件端口都是随机启动+自动发现。。。
当前我也没好的办法。

**Comment by laiwei** [comment]
你说的是 vip 吧？这个不是 open-falcon 范畴内的。

@jschunlei
