### ISSUE TITLE
callback 只支持http get方式回调

### ISSUE THREAD

**Issue by shuaifes** [open-falcon/dashboard#71]
这个callback的URL会被调用，被调用后会把告警信息返回到这个URL么？这个机制是什么？谢谢

**Comment by laiwei** [comment]
![image](https://user-images.githubusercontent.com/792850/43523790-18218b54-95d0-11e8-80f1-c7ded912637f.png)
https://github.com/open-falcon/falcon-plus/blob/master/common/model/event.go
