### ISSUE TITLE
./env/bin/pip install -r pip_requirements.txt -i https://pypi.douban.com/simple

### ISSUE THREAD

**Issue by Mrhjx2** [open-falcon/dashboard#75]
hello!
the dashboard
when installed on centos6.6 python2.7,report the question "CertificateError: hostname 'pypi.doubanio.com' doesn't match '*.ucdl.pp.uc.cn'"
it appeared in virtualenv environment, but it was installed sucessfully in system python environment 
./env/bin/pip install -r pip_requirements.txt -i https://pypi.douban.com/simple

**Comment by yangyujie1320** [comment]
run this: ./env/bin/pip install -r pip_requirements.txt

**Comment by kiddkyd1412** [comment]
vi  pip_requirements.txt
edit      gunicorn ~> 19.5.0
to         gunicorn == 19.5.0

fu*k

**Comment by laiwei** [comment]
@kiddkyd1412  fixed https://github.com/open-falcon/dashboard/commit/b487bc60e3b19fba1f1594c0027f128f17abfd07

@Mrhjx2  fixed https://github.com/open-falcon/dashboard/commit/8120ef889c64ed03d0d3f67096096725ffe7dd2d
