### ISSUE TITLE
dashboard中的图表的数据显示单位

### ISSUE THREAD

**Issue by freedomkk-qfeng** [open-falcon/dashboard#8]
现在图表的数据显示单位都是按1000计算的。即1000=1K，100000=1M，....
但是对于磁盘容量，网络数据等，似乎按1024计算更为合适。
是否可以在dashboard的图边上增加个选项，选择计算方式为1000还是1024~~

**Comment by maobaolong** [comment]
这个应该修改为1024

**Comment by laiwei** [comment]
这个K、M 指的是10的三次方、10的6次方的简写。。。改为1024也有歧义
