### ISSUE TITLE
NoneType object has no attribute 'cursor'

### ISSUE THREAD

**Issue by w564791** [open-falcon/dashboard#87]
def execute(self, *a, **kw):
        cursor = kw.pop('cursor', None)
        try:
            cursor = cursor or self.get_conn().cursor()
            cursor.execute(*a, **kw)
        except (AttributeError, MySQLdb.OperationalError):
            self.conn and self.conn.close()
            self.conn = None
            cursor = self.get_conn().cursor()
            cursor.execute(*a, **kw)
        return cursor

报错直接致命第71行，这里为什么又要连一次呢，上面不是已经捕获了错误了么，except里面再连一次，就捕获不到错误了啊

**Comment by laiwei** [comment]
https://github.com/open-falcon/dashboard/issues/106

**Comment by iceqing** [comment]
参考[#65](https://github.com/open-falcon/falcon-plus/issues/65)
