### ISSUE TITLE
template 页面 metric 过滤不起作用

### ISSUE THREAD

**Issue by sdvdxl** [open-falcon/dashboard#90]
不管输入什么（2个字符以上）都是显示一样的列表
![xnip2018-02-55_17-45-06](https://user-images.githubusercontent.com/3821540/36628962-79873582-198a-11e8-98f0-a0572533937e.jpg)

**Comment by laiwei** [comment]
@sdvdxl 有进一步更新吗

**Comment by yuline** [comment]
template 页面 metric 过滤不起作用

**Comment by yuline** [comment]
https://github.com/open-falcon/dashboard/pull/101

**Comment by laiwei** [comment]
@sdvdxl fixed:)
