### ISSUE TITLE
New user sign up error: unauthorized

### ISSUE THREAD

**Issue by lxtxlxl** [open-falcon/dashboard#92]
How to solve this problem?  dashboard was  installed complete，and  new user register throw abnormal ：unauthorized
thanks！

**Comment by laiwei** [comment]
Is there more additional detail information such as screenshots or log? @lxtxlxl

**Comment by lxtxlxl** [comment]
I'm  so sorry,  checked the api  log, found a result：8081 port was used by docker continer ，this issue was resolved，thanks replied me ！
