### ISSUE TITLE
dashboard可以出图但是screen无法出图

### ISSUE THREAD

**Issue by popzyw** [open-falcon/dashboard#97]
如题，从dashboard勾选后可以出图，但是在screen中配置之后完全没反应

**Comment by popzyw** [comment]
![image](https://user-images.githubusercontent.com/38308692/38719265-8c67d8b4-3f23-11e8-8f56-b0a8efe2bf40.png)

**Comment by popzyw** [comment]
![image](https://user-images.githubusercontent.com/38308692/38719365-2d433a3a-3f24-11e8-9d1d-1d1104a5b2bd.png)

**Comment by popzyw** [comment]
![image](https://user-images.githubusercontent.com/38308692/38719381-42ca92ea-3f24-11e8-8287-be838e0d0396.png)

**Comment by popzyw** [comment]
@laiwei 还是没有好，浏览器调试时候页面都没有，请问screen和dashboard中的图不是一个数据源吗？

**Comment by xiaomaimai363** [comment]
问题已定位，主机名的‘hostname#ip’命名方式，踩到了Open-Falcon API的查询限制，#是特殊字符，用于分割查询时的host#item#tag；因此无法创建出screen图表。
